const { EmbedBuilder, ActionRowBuilder, ButtonBuilder, StringSelectMenuBuilder, ButtonStyle, AttachmentBuilder } = require('discord.js');
const config = require('../config');
const fs = require('fs');
const path = require('path');

class UIComponents {
    constructor(uiConfig) {
        this.config = uiConfig || config;
        this.theme = this.config.theme || {};
    }

    createSuccessEmbed(title, description, fields = []) {
        const embed = new EmbedBuilder()
            .setColor(0x00FF9D) // Neon Mint
            .setTitle(`✨ ${title}`)
            .setDescription(`\`\`\`ansi\n\u001b[0;32mSUCCESSFUL OPERATION\u001b[0m\n\`\`\`\n${description}\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`)
            .setTimestamp()
            .setFooter({ text: 'AXML Studio Pro' });

        if (fields.length > 0) embed.addFields(fields);
        return embed;
    }

    createErrorEmbed(errorCode, errorMessage, suggestions = []) {
        const embed = new EmbedBuilder()
            .setColor(0xFF4C4C) // Bright Red
            .setTitle(`🛑 SYSTEM ERROR DETECTED`)
            .setDescription(`\`\`\`ansi\n\u001b[0;31mERROR CODE: ${errorCode}\u001b[0m\n\`\`\`\n**Incident Report:**\n> ${errorMessage}\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`)
            .setTimestamp()
            .setFooter({ text: 'System Diagnostics | AXML Engine' });

        if (suggestions.length > 0) {
            embed.addFields({
                name: '🛠️ Potential Resolutions',
                value: suggestions.map(s => `• ${s}`).join('\n'),
                inline: false
            });
        }
        return embed;
    }

    createProcessingEmbed(stage, progress = 0) {
        const barLength = 15;
        const filled = Math.round((progress / 100) * barLength);
        const empty = barLength - filled;
        const bar = '█'.repeat(filled) + '░'.repeat(empty);

        return new EmbedBuilder()
            .setColor(0x7C3AED) // Deep Purple
            .setTitle('💎 **AXML COMPUTING ENGINE**')
            .setDescription([
                `\`\`\`ansi`,
                `\u001b[1;35mSTAGE:\u001b[0m \u001b[0;37m${stage.toUpperCase()}\u001b[0m`,
                `\u001b[1;37m${bar}\u001b[0m \u001b[1;35m${progress}%\u001b[0m`,
                `\`\`\``
            ].join('\n'))
            .setFooter({ text: 'Processing high-fidelity audio data...' });
    }

    createRenderCompleteEmbed(meta, duration) {
        return new EmbedBuilder()
            .setColor(0x00FBFF)
            .setTitle(`🎹 AXML Studio Pro | ${meta.title || 'Untitled'}`)
            .setDescription(`**Artist:** ${meta.artist || 'Unknown'}\n**Genre:** ${meta.genre || 'N/A'}`)
            .addFields(
                { name: 'Tempo', value: `${meta.tempo || 120} BPM`, inline: true },
                { name: 'Key', value: meta.key || 'C', inline: true },
                { name: 'Duration', value: this.formatDuration(duration), inline: true }
            )
            .setTimestamp()
            .setFooter({ text: 'Powered by AXML Engine' });
    }

    createAIGenerationEmbed(prompt, analysis, meta, duration) {
        const truncatedPrompt = prompt.length > 60 ? prompt.substring(0, 60) + '...' : prompt;

        return new EmbedBuilder()
            .setColor(0x00FBFF) // Cyan
            .setTitle('🌌 **AI MASTERPIECE GENERATED**')
            .setDescription(`> *"${truncatedPrompt}"*\n\n**Composition Details:**\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`)
            .addFields(
                {
                    name: '🎹 **Musicality**',
                    value: `\`\`\`ansi\n\u001b[1;36mKey:\u001b[0m   ${meta.key || 'C'}\n\u001b[1;36mTempo:\u001b[0m ${meta.tempo || 120} BPM\n\u001b[1;36mScale:\u001b[0m  Major\n\`\`\``,
                    inline: false
                },
                {
                    name: '📈 **Analysis**',
                    value: `\`\`\`ansi\n\u001b[1;35mGenre:\u001b[0m  ${analysis.genre}\n\u001b[1;35mMood:\u001b[0m   ${analysis.mood || 'Dynamic'}\n\u001b[1;35mTime:\u001b[0m   ${duration.toFixed(1)}s\n\`\`\``,
                    inline: false
                }
            )
            .setTimestamp()
            .setFooter({ text: 'Generated by AXML Maestro Pro' });
    }

    createTransportControls() {
        return new ActionRowBuilder().addComponents(
            new ButtonBuilder().setCustomId('btn_play').setLabel('Play').setEmoji('▶️').setStyle(ButtonStyle.Success),
            new ButtonBuilder().setCustomId('btn_pause').setLabel('Pause').setEmoji('⏸️').setStyle(ButtonStyle.Secondary),
            new ButtonBuilder().setCustomId('btn_stop').setLabel('Stop').setEmoji('⏹️').setStyle(ButtonStyle.Danger)
        );
    }

    createEditorControls() {
        return new ActionRowBuilder().addComponents(
            new ButtonBuilder().setCustomId('btn_edit_code').setLabel('Edit AXML').setEmoji('✏️').setStyle(ButtonStyle.Primary),
            new ButtonBuilder().setCustomId('btn_instruments').setLabel('Instruments').setEmoji('🎹').setStyle(ButtonStyle.Secondary),
            new ButtonBuilder().setCustomId('btn_mixer').setLabel('Mixer').setEmoji('🎚️').setStyle(ButtonStyle.Secondary)
        );
    }

    createFileOperations() {
        return new ActionRowBuilder().addComponents(
            new ButtonBuilder().setCustomId('btn_import').setLabel('Import').setEmoji('📥').setStyle(ButtonStyle.Secondary),
            new ButtonBuilder().setCustomId('btn_export_wav').setLabel('Export WAV').setEmoji('💾').setStyle(ButtonStyle.Primary)
        );
    }

    formatDuration(seconds) {
        const mins = Math.floor(seconds / 60);
        const secs = Math.floor(seconds % 60);
        return `${mins}:${secs.toString().padStart(2, '0')}`;
    }

    createHelpEmbed(category = 'all') {
        const embed = new EmbedBuilder()
            .setColor(0x00FBFF)
            .setTitle('🎹 **AXML Studio Pro**')
            .setDescription('*AI-Powered Music Production Bot*\n━━━━━━━━━━━━━━━━━━━━━\n')
            .setTimestamp();

        if (category === 'all') {
            embed.addFields(
                { name: '🎨 CREATIVE', value: '`~gen`, `~template`, `~render`', inline: true },
                { name: '🔊 STUDIO', value: '`~play`, `~stop`', inline: true },
                { name: '🛠️ TOOLS', value: '`~transpose`, `~tempo`, `~profile`', inline: true }
            );
        }
        return embed;
    }

    createStatsEmbed(stats) {
        return new EmbedBuilder()
            .setColor(0x00FBFF)
            .setTitle('🛰️ **SYSTEM STATS**')
            .setDescription([
                '```ansi',
                `\u001b[1;36mGUILDS:\u001b[0m  \u001b[1;37m${stats.guilds}\u001b[0m`,
                `\u001b[1;36mUSERS:\u001b[0m   \u001b[1;37m${stats.users}\u001b[0m`,
                '```'
            ].join('\n'))
            .addFields(
                { name: '🤖 ENGINE', value: `\`\`\`Uptime: ${stats.uptime}\nMemory: ${stats.memoryMB}MB\`\`\``, inline: false }
            );
    }

    createProfileEmbed(user, targetUser, projects, activity) {
        return new EmbedBuilder()
            .setColor(0x7C3AED)
            .setTitle(`👤 **Profile: ${targetUser.username}**`)
            .setThumbnail(targetUser.displayAvatarURL({ dynamic: true }))
            .setDescription(`\`\`\`ansi\n\u001b[1;37mRANK:\u001b[0m \u001b[1;36mPRODUCER\u001b[0m\n\`\`\``)
            .addFields(
                { name: '📊 STATS', value: `\`\`\`Generations: ${user.stats?.generationsTotal || 0}\nProjects: ${projects.length}\`\`\``, inline: false }
            );
    }

    createHelpMenu() {
        return new ActionRowBuilder().addComponents(
            new StringSelectMenuBuilder()
                .setCustomId('help_menu_select')
                .setPlaceholder('Browse Categories...')
                .addOptions([
                    { label: 'Home', value: 'all', emoji: '🏠' },
                    { label: 'Creation', value: 'creation', emoji: '🎹' },
                    { label: 'Tools', value: 'tools', emoji: '🛠️' }
                ])
        );
    }

    createSessionsEmbed(sessions) {
        return new EmbedBuilder()
            .setColor(0x00FBFF)
            .setTitle('🎹 **YOUR ACTIVE SESSIONS**')
            .setDescription(sessions.map((s, i) => `${i + 1}. **${s.parsed?.metadata?.title || 'Untitled'}**\n   └ ID: \`${s.sessionId}\` • Tracks: ${s.parsed?.tracks?.length || 0}`).join('\n') || 'No active sessions.')
            .setTimestamp()
            .setFooter({ text: 'Use ~sessions info [id] for details' });
    }

    createProjectListEmbed(projects) {
        return new EmbedBuilder()
            .setColor(0x00FBFF)
            .setTitle('📂 **PROJECT LIBRARY**')
            .setDescription(projects.map((p, i) => `${i + 1}. **${p.name}**\n   └ ID: \`${p.id}\` • Created: ${new Date(p.createdAt).toLocaleDateString()}`).join('\n') || 'No projects saved yet.')
            .setTimestamp();
    }

    createRateLimitEmbed(retryAfter) {
        return new EmbedBuilder()
            .setColor(0xFFAA00)
            .setTitle('⏱️ **RATE LIMIT ACTIVE**')
            .setDescription(`\`\`\`ansi\n\u001b[1;33mCOOLDOWN REQUIRED\u001b[0m\n\`\`\`\nPlease wait **${Math.ceil(retryAfter / 1000)}s** before executing this command again.`)
            .setFooter({ text: 'Anti-Spam System' });
    }

    async getCommonIconAttachments(client, iconNames) {
        const attachments = [];
        const assetsDir = this.config.paths?.assets || './assets';

        for (const name of iconNames) {
            let iconPath = path.join(assetsDir, 'svg', name);

            // Try PNG if SVG doesn't exist
            if (!fs.existsSync(iconPath)) {
                iconPath = iconPath.replace('.svg', '.png');
            }

            if (fs.existsSync(iconPath)) {
                attachments.push(new AttachmentBuilder(iconPath, { name: path.basename(iconPath) }));
            }
        }
        return attachments;
    }

    getCommonIcons(iconNames) {
        const attachments = [];
        const assetsDir = this.config.paths?.assets || './assets';

        for (const name of iconNames) {
            let iconPath = path.join(assetsDir, 'svg', name);
            if (!fs.existsSync(iconPath)) {
                iconPath = iconPath.replace('.svg', '.png');
            }

            if (fs.existsSync(iconPath)) {
                attachments.push(new AttachmentBuilder(iconPath, { name: path.basename(iconPath) }));
            }
        }
        return attachments;
    }
}

module.exports = UIComponents;
